#!/usr/bin/env bash
#REF: https://raw.githubusercontent.com/bitcoin-core/docs/master/gitian-building/gitian-building-setup-gitian-debian.md

apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean
#apt-get -o Dpkg::Options::='--force-confold' --force-yes -fuy install
#apt-get -o Dpkg::Options::='--force-confold' --force-yes -fuy upgrade

apt-get install sudo
apt-get install wget
apt-get install python3
apt-get install debootstrap
apt-get install lsb-release
apt-get install git
apt-get install vim
apt-get install ruby
apt-get install apt-cacher-ng
apt-get install qemu-utils
apt-get install lxc
apt-get install python-cheetah
apt-get install parted
apt-get install kpartx
apt-get install bridge-utils
apt-get install make
apt-get install ubuntu-archive-keyring
apt-get install curl
apt-get install firewalld
apt-get install bionic
apt-get install lsb-release
#apt-get install docker 
apt-get install cgroup-tools
apt-get install libtool
apt-get install pkg-config
apt-get install build-essential
apt-get install dpkg-dev
apt-get install fake-root
apt-get install libalgorithm-diff-perl
apt-get install libalgorithm-diff-xs-perl
apt-get install libfakeroot
apt-get install debian-keyring
apt-get install libdb4.8 libdb4.8++
apt-get install pacman
apt-get install pciutils
apt-get install subversion
apt-get install language-pack-en
apt-get install wget
apt-get install linux-image-generic
apt-get install grub-pc
apt-get install openssh-server
apt-get install wget
apt-get install libdb++-dev

pacman -S git base-devel boost libevent python

sudo adduser gitianuser
sudo adduser gitianuser sudo

echo $PWD
cd /home/gitianuser
echo $PWD


	#begin setup
	echo "TYPE 'exit' then press RETURN"
	#sudo -s
	# the version of lxc-start in Debian needs to run as root, so make sure
	# that the build script can execute it without providing a password
	echo "%sudo ALL=NOPASSWD: /usr/bin/lxc-start" > /etc/sudoers.d/gitian-lxc
	echo "%sudo ALL=NOPASSWD: /usr/bin/lxc-execute" >> /etc/sudoers.d/gitian-lxc
	# make /etc/rc.local script that sets up bridge between guest and host
	echo '#!/bin/sh -e' > /etc/rc.local
	echo 'brctl addbr br0' >> /etc/rc.local
	echo 'ip addr add 10.0.3.1/24 broadcast 10.0.3.255 dev br0' >> /etc/rc.local
	echo 'ip link set br0 up' >> /etc/rc.local
	echo 'firewall-cmd --zone=trusted --add-interface=br0' >> /etc/rc.local
	echo 'exit 0' >> /etc/rc.local
	chmod +x /etc/rc.local
	# make sure that USE_LXC is always set when logging in as gitianuser,
	# and configure LXC IP addresses
	echo 'export USE_LXC=1' >> /home/gitianuser/.profile
	echo 'export GITIAN_HOST_IP=10.0.3.1' >> /home/gitianuser/.profile
	echo 'export LXC_GUEST_IP=10.0.3.5' >> /home/gitianuser/.profile

	#
	wget http://archive.ubuntu.com/ubuntu/pool/universe/v/vm-builder/vm-builder_0.12.4+bzr494.orig.tar.gz
	echo "76cbf8c52c391160b2641e7120dbade5afded713afaa6032f733a261f13e6a8e  vm-builder_0.12.4+bzr494.orig.tar.gz" | sha256sum -c
	# (verification -- MUST return OK)
	tar -zxvf vm-builder_0.12.4+bzr494.orig.tar.gz

cd /home/gitianuser
echo $PWD
cd vm-builder-0.12.4+bzr494
#    runuser -l gitianuser -c 'sudo python3 setup.py install'
	gitianuser ALL = NOPASSWORD: /home/gitianuser/vm-builder-0.12.4+bzr494/setup.py install
#	./gitian-build.py --setup
	#python3 setup.py install

cd /home/gitianuser
echo $PWD

	read -p 'ENTER your Github.com username: ' GITHUB_USER_NAME
	#read -sp 'Password: ' GITHUB_USER_PASSWORD
	echo
	echo Thankyou $GITHUB_USER_NAME
	read -p 'ENTER your Github.com user email: ' GITHUB_USER_EMAIL
	echo
	echo Thankyou $GITHUB_USER_NAME for your email.
	read -p 'ENTER your public gpg signing key id: ' PUBLIC_GPG_SIGNING_KEY_ID
	echo
	echo Thankyou $GITHUB_USER_NAME for public gpg signing key id.

	echo "configuring git"
	git config --global user.name GITHUB_USER_NAME
	git config --global user.email GITHUB_USER_EMAIL
	
	git clone https://github.com/bitcoin-core/gitian.sigs.git

cd /home/gitianuser/gitian.sigs
echo $PWD

	git remote add $GITHUB_USER_NAME  https://github.com/$GITHUB_USER_NAME/gitian.sigs.git

cd /home/gitianuser
echo $PWD

	git clone https://github.com/devrandom/gitian-builder.git
	git clone https://github.com/bitcoin/bitcoin
	git clone https://github.com/bitcoin-core/bitcoin-detached-sigs.git

cd /home/gitianuser/gitian-builder
echo $PWD

	bin/make-base-vm --lxc --arch amd64 --suite bionic # For releases >= 0.17.0
	bin/make-base-vm --lxc --arch amd64 --suite trusty # For releases <  0.17.0

cd /home/gitianuser
echo $PWD

	read -p 'Rebuild base? Y/n ' REBUILD
	if [ $REBUILD == 'Y' ];then
		rm -rf /home/gitianuser/gitian-builder/base-*
		rm -rf /home/gitianuser/gitian-builder/inputs
		rm -rf /home/gitianuser/vm-builder*.gz.*
	cd /home/gitianuser/gitian-builder
		bin/make-base-vm --lxc --arch amd64 --suite bionic # For releases >= 0.17.0
		bin/make-base-vm --lxc --arch amd64 --suite trusty # For releases <  0.17.0
	fi

mkdir /home/gitianuser/gitian-builder/inputs
cd /home/gitianuser/gitian-builder/inputs
echo $PWD

	wget  https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.11.sdk.tar.xz
	mv MacOSX10.11.sdk.tar.xz MacOSX10.11.sdk.tar.gz

cp /home/gitianuser/bitcoin/contrib/gitian-build.py /home/gitianuser/.
cd /home/gitianuser
echo $PWD
sudo chmod +x gitian-build.py

	read -p 'ENTER version (example: 0.19.0rc3): ' VERSION
	sudo ./gitian-build.py -o l -o w -o m --buildsign --url https://github.com/randymcmillan/bitcoin.git  $GITHUB_USER_NAME $VERSION

echo $PWD
